/* Copyright (C) 2025 Pedro Henrique / phkaiser13
* build-windows.yml
* This GitHub Actions workflow builds, tests, and packages the gitph project on Windows.
* It uses the MSVC toolchain, manages dependencies with vcpkg, and integrates Rust modules.
* For tagged pushes, it creates a comprehensive .zip release package including all
* necessary runtime DLLs from vcpkg, ensuring the final executable is self-contained.
 * SPDX-License-Identifier: Apache-2.0 */

name: Build gitph (Windows)

on:
  push:
    branches: [ "main" ]
    # Added trigger for tags to enable release packaging
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    # Environment variables required for vcpkg and the build process
    env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      RUSTFLAGS: ""

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 is important for workflows that need tag/branch history
          fetch-depth: 0

      # Step 2: Install a specific version of CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.29.3'

      # Step 3: Install Ninja build system using Chocolatey package manager
      - name: Install Ninja
        run: choco install ninja -y

      # Step 4: Install vcpkg and required C++ libraries for the x64-windows (MSVC) triplet.
      # This is a critical step for dependency management on Windows.
      - name: Install vcpkg and libraries
        run: |
          git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
          cd $env:VCPKG_ROOT
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install curl lua nlohmann-json --triplet x64-windows
        shell: pwsh

      # Step 5: Set up the Rust toolchain
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

          
      # Step 7: Debugging step to list installed vcpkg files and verify paths
      - name: Debug vcpkg installed files
        run: |
          Write-Host "VCPKG_ROOT = $env:VCPKG_ROOT"
          Get-ChildItem -Path "${{ env.VCPKG_ROOT }}\installed\x64-windows\share" -Recurse -Depth 2 | Select-Object -First 200
          Get-ChildItem -Path "${{ env.VCPKG_ROOT }}\installed\x64-windows\lib" -Recurse -Depth 1 | Select-Object -First 200
        shell: pwsh
        
      # Step 8: Configure the project using CMake.
      # This uses the "Visual Studio 17 2022" generator and points to the vcpkg toolchain file.
      # The flags explicitly help CMake find the libraries installed by vcpkg.
      - name: Configure CMake (MSVC, Visual Studio generator)
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}\scripts\buildsystems\vcpkg.cmake" `
            -DCMAKE_PREFIX_PATH="${{ env.VCPKG_ROOT }}\installed\x64-windows\share" `
            -DLua_FOUND=TRUE `
            -DLUA_INCLUDE_DIR="${{ env.VCPKG_ROOT }}\installed\x64-windows\include" `
            -DLUA_LIBRARY="${{ env.VCPKG_ROOT }}\installed\x64-windows\lib\lua.lib" `
            -DLUA_LIBRARIES="${{ env.VCPKG_ROOT }}\installed\x64-windows\lib\lua.lib" `
            -DCMAKE_BUILD_TYPE=Release
        shell: pwsh

      # Step 9: Build the project using the 'Release' configuration.
      - name: Build Project
        run: cmake --build build --config Release --parallel
        shell: pwsh

      # Step 10: Run tests if they exist, continuing on error.
      - name: Run tests
        run: |
          cd build
          ctest -C Release --output-on-failure
        shell: pwsh
        continue-on-error: true

      # Step 11: Ensure Release output directory exists for DLLs.
      # This step is crucial for tagged builds to prepare the final package.
      - name: Ensure Release Output Directory Exists
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          New-Item -ItemType Directory -Path "build/bin/Release" -Force
        shell: pwsh

      # Step 12: Copy Runtime DLLs for the Release Package.
      # These DLLs are required for the gitph.exe to run without external dependencies.
      - name: Copy Runtime DLLs for Release Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $vcpkgBinPath = "${{ env.VCPKG_ROOT }}\installed\x64-windows\bin"
          $targetPath = "build/bin/Release"
          
          Write-Host "Copying DLLs from $vcpkgBinPath to $targetPath"
          Copy-Item -Path "$vcpkgBinPath\lua.dll" -Destination "$targetPath\" -Force
          Copy-Item -Path "$vcpkgBinPath\libcurl.dll" -Destination "$targetPath\" -Force
          Copy-Item -Path "$vcpkgBinPath\libcrypto-3-x64.dll" -Destination "$targetPath\" -Force
          Copy-Item -Path "$vcpkgBinPath\libssl-3-x64.dll" -Destination "$targetPath\" -Force
          Copy-Item -Path "$vcpkgBinPath\zlib1.dll" -Destination "$targetPath\" -Force
          
          Write-Host "Contents of $targetPath after copying DLLs:"
          Get-ChildItem -Path "$targetPath" | Select-Object Name, Length
        shell: pwsh

      # Step 13: Create Release ZIP Archive.
      # This step bundles the executable, copied DLLs, plugins, and license into a single ZIP.
      - name: Create Release ZIP Archive
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $tagName = "${{ github.ref_name }}"
          $zipFileName = "gitph-windows-x64-$tagName.zip"
          
          # Create a temporary directory for packaging
          $packageDir = "gitph-package"
          New-Item -ItemType Directory -Path $packageDir -Force
          
          # Copy executable and DLLs from the Release build directory
          # Assuming gitph.exe is located at build/bin/Release/gitph.exe
          Write-Host "Copying gitph.exe and DLLs to package directory..."
          Copy-Item -Path "build/bin/Release/gitph.exe" -Destination "$packageDir/" -Force
          Copy-Item -Path "build/bin/Release/*.dll" -Destination "$packageDir/" -Force
          
          # Copy plugins (recursively)
          Write-Host "Copying plugins..."
          Copy-Item -Path "src/plugins/" -Destination "$packageDir/" -Recurse -Force
          
          # Copy LICENSE file
          Write-Host "Copying LICENSE file..."
          Copy-Item -Path "LICENSE" -Destination "$packageDir/" -Force
          
          # Create the ZIP archive
          Write-Host "Creating ZIP archive: $zipFileName"
          Compress-Archive -Path "$packageDir/*" -DestinationPath "$zipFileName" -Force
          
          Write-Host "Successfully created $zipFileName"
          Get-ChildItem -Path "." -Filter "*.zip" | Select-Object Name, Length
        shell: pwsh

      # Step 14: Upload Release Artifact (for tags).
      # This makes the generated ZIP file available as a build artifact.
      - name: Upload Release Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: gitph-windows-x64-release-${{ github.ref_name }}
          path: gitph-windows-x64-${{ github.ref_name }}.zip

      # Step 15: Upload CI Build Artifacts (for non-tag builds).
      # This step remains for regular CI builds to provide intermediate artifacts.
      - name: Upload CI Build Artifacts (not for tags)
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: gitph-build-artifacts-windows-x64
          # Corrected paths for executable, modules, plugins, and license
          path: |
            build/bin/
            src/plugins/
            LICENSE
