# Copyright (C) 2025 Pedro Henrique / phkaiser13
# Fedora-like_ci.yml - Workflow de Integração Contínua para o projeto gitph em Fedora Linux.
#
# Esta é uma versão corrigida e funcional do workflow, alinhada com as melhores
# práticas dos outros CI do projeto.
# SPDX-License-Identifier: Apache-2.0

name: Build and Release gitph (Fedora-like Linux)

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test (Fedora Container)
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências de sistema (Fedora)
        run: |
          # Atualiza os metadados e instala todas as dependências de uma vez
          dnf -y update
          dnf install -y \
            gcc-c++ \
            make \
            cmake \
            pkgconf-pkg-config \
            lua-devel \
            libcurl-devel \
            openssl-devel \
            nlohmann-json-devel \
            binutils \
            git \
            tar \
            gzip \
            which
          # Limpa o cache para otimizar
          dnf clean all

      - name: Configurar ambiente Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Configurar ambiente Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cache do Rust
        uses: Swatinem/rust-cache@v2

      - name: Configurar e Compilar com CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel

      - name: Rodar testes unitários (se existirem)
        if: always()
        run: |
          if [ -f build/CTestTestfile.cmake ]; then
            (cd build && ctest --output-on-failure)
          else
            echo "Nenhum teste configurado (CTestTestfile.cmake não encontrado)."
          fi

      - name: Upload dos artefatos de build
        uses: actions/upload-artifact@v4
        with:
          name: gitph-build-artifacts-fedora
          path: |
            build/bin/
            src/plugins/
            LICENSE


