# Copyright (C) 2025 Pedro Henrique / phkaiser13
# main_ci_macos.yml - Continuous Integration workflow for the gitph project on macOS.
#
# This workflow automates the build process of the application for macOS,
# supporting both Intel (x86_64) and Apple Silicon (arm64) architectures.
# SPDX-License-Identifier: Apache-2.0

name: Build gitph (macOS & Darwin systems)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build for macOS (${{ matrix.arch }})
    strategy:
      matrix:
        include:
          - os: macos-13 # Intel
            arch: x86_64
          - os: macos-14 # Apple Silicon
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Homebrew)
        run: brew install cmake pkg-config lua curl nlohmann-json

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Compile Project
        run: cmake --build build --parallel
