name: CI Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      - name: Setup Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake liblua5.4-dev libcurl4-openssl-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install cmake lua curl

      - name: Setup Vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        uses: microsoft/vcpkg-action@v5
        id: vcpkg
        with:
          vcpkg-version: 'latest'
          pkgs: lua,curl

      - name: Configure CMake (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cmake -S . -B build \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg.outputs.vcpkg-root }}/scripts/buildsystems/vcpkg.cmake

      - name: Configure CMake (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: cmake -S . -B build

      - name: Build Project
        run: cmake --build build --parallel

      - name: Run tests
        run: echo "No automated tests configured yet. Build successful."
