# .github/workflows/publish-packages.yml
name: 'Publish to Package Managers'

on:
  release:
    types: [published]

jobs:
  publish:
    name: Update Homebrew, AUR, and vcpkg
    runs-on: ubuntu-latest
    steps:
      - name: 'Get release version from tag'
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" | sed -e 's/v//' >> $GITHUB_ENV

      - name: 'Download source tarball and calculate checksums'
        run: |
          TARBALL_URL="https://github.com/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"
          curl -L -o source.tar.gz "$TARBALL_URL"
          
          # Calcula e armazena ambos os checksums
          echo "TARBALL_SHA256=$(sha256sum source.tar.gz | awk '{print $1}')" >> $GITHUB_ENV
          echo "TARBALL_SHA512=$(sha512sum source.tar.gz | awk '{print $1}')" >> $GITHUB_ENV

      # --- Seção para atualizar o Homebrew Tap ---
      - name: 'Checkout Homebrew Tap repository'
        uses: actions/checkout@v4
        with:
          repository: 'phkaiser/homebrew-tap'
          token: ${{ secrets.PAT_TOKEN }}
          path: 'homebrew-tap'

      - name: 'Update Homebrew formula'
        run: |
          sed -i "s|url \".*\"|url \"https://github.com/${{ github.repository }}/archive/refs/tags/v${{ env.RELEASE_VERSION }}.tar.gz\"|" homebrew-tap/Formula/gitph.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ env.TARBALL_SHA256 }}\"|" homebrew-tap/Formula/gitph.rb
        
      - name: 'Commit and push changes to Homebrew Tap'
        run: |
          cd homebrew-tap
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/gitph.rb
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update gitph formula to v${{ env.RELEASE_VERSION }}"
            git push
          else
            echo "No changes to commit for Homebrew."
          fi
          cd ..

      # --- Seção para atualizar o repositório do AUR ---
      - name: 'Checkout AUR repository'
        uses: actions/checkout@v4
        with:
          repository: 'phkaiser/aur-gitph'
          token: ${{ secrets.PAT_TOKEN }}
          path: 'aur-gitph'

      - name: 'Update PKGBUILD'
        run: |
          cd aur-gitph
          sed -i "s/pkgver='.*'/pkgver='${{ env.RELEASE_VERSION }}'/" PKGBUILD
          sed -i "s/sha256sums=('.*')/sha256sums=('${{ env.TARBALL_SHA256 }}')/" PKGBUILD
          makepkg --printsrcinfo > .SRCINFO
          
      - name: 'Commit and push changes to AUR repository'
        run: |
          cd aur-gitph
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add PKGBUILD .SRCINFO
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update gitph PKGBUILD to ${{ env.RELEASE_VERSION }}"
            git push
          else
            echo "No changes to commit for AUR."
          fi
          cd ..
          
      # --- (NOVO) Seção para atualizar o vcpkg Registry ---
      - name: 'Checkout vcpkg registry repository'
        uses: actions/checkout@v4
        with:
          # Assumindo que o nome do repositório é 'vcpkg-registry'
          repository: 'phkaiser/vcpkg-registry'
          token: ${{ secrets.PAT_TOKEN }}
          path: 'vcpkg-registry'

      - name: 'Update vcpkg port files'
        run: |
          # Atualiza a versão no vcpkg.json
          sed -i 's|\"version\": \".*\"|\"version\": \"${{ env.RELEASE_VERSION }}\"|' vcpkg-registry/ports/gitph/vcpkg.json
          
          # Atualiza a tag (REF) e o hash (SHA512) no portfile.cmake
          sed -i 's|REF \".*\"|REF \"v${{ env.RELEASE_VERSION }}\"|' vcpkg-registry/ports/gitph/portfile.cmake
          sed -i 's|SHA512 \".*\"|SHA512 \"${{ env.TARBALL_SHA512 }}\"|' vcpkg-registry/ports/gitph/portfile.cmake
          
      - name: 'Commit and push changes to vcpkg registry'
        run: |
          cd vcpkg-registry
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ports/gitph/vcpkg.json ports/gitph/portfile.cmake
          if ! git diff --staged --quiet; then
            git commit -m "chore(gitph): Update port to v${{ env.RELEASE_VERSION }}"
            git push
          else
            echo "No changes to commit for vcpkg."
          fi
