# Copyright (C) 2025 Pedro Henrique / phkaiser13
# Windows-ci.yml - Workflow de Integração Contínua para o projeto gitph no Windows.
#
# Automatiza build, testes e upload de artefatos no Windows.
# SPDX-License-Identifier: Apache-2.0

name: Build do gitph (Windows)

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build e Teste no Windows
    runs-on: windows-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Instala Visual Studio Build Tools (obrigatório para compilação C++)
      - name: Instalar Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest'

      # 3. Instalar CMake via ação oficial
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.9.0
        with:
          cmake-version: '3.26.4' # ou a versão que preferir

      # 4. Instalar vcpkg e as dependências via vcpkg
      - name: Instalar vcpkg e dependências
        shell: powershell
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat

          # Instala as bibliotecas necessárias
          .\vcpkg.exe install lua:x64-windows curl:x64-windows nlohmann-json:x64-windows pkgconf:x64-windows

          # Opcional: integração do vcpkg com o MSBuild
          .\vcpkg.exe integrate install

      # 5. Configurar variáveis de ambiente para usar o toolchain do vcpkg
      - name: Configurar toolchain vcpkg
        shell: powershell
        run: |
          echo "##vso[task.setvariable variable=VCPKG_ROOT]${{ github.workspace }}\vcpkg"
          echo "##vso[task.setvariable variable=CMAKE_TOOLCHAIN_FILE]${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"

      # 6. Configurar CMake, passando o toolchain do vcpkg
      - name: Configurar CMake e Build
        shell: powershell
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake
          cmake --build build --parallel

      # 7. Upload dos artefatos de build
      - name: Upload dos artefatos de build
        uses: actions/upload-artifact@v4
        with:
          name: gitph-build-artifacts
          path: |
            build\bin\
            src\plugins\
            LICENSE
