# Copyright (C) 2025 Pedro Henrique / phkaiser13
# windows_build.yml - Workflow de Integração Contínua para Windows.
#
# Este workflow valida a compilação do projeto no ambiente Windows,
# garantindo que todas as dependências (C++, Rust, Go) são resolvidas
# e que o projeto compila com sucesso usando o toolchain do Visual Studio
# e o gerenciador de pacotes vcpkg.
#
# SPDX-License-Identifier: Apache-2.0

name: Build para Windows

# Gatilhos do workflow:
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    name: Build em Windows (MSVC)
    runs-on: windows-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # 3. Configura o ambiente Rust (com cache integrado)
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      # 4. Setup vcpkg e Instalar dependências
      #    CORREÇÃO 1: Adicionado 'run-vcpkg-integrate-install: true'.
      #    Isso integra o vcpkg diretamente com o ambiente MSBuild do runner.
      #    Agora, o compilador encontrará os headers (curl.h, nlohmann/json.hpp)
      #    para TODOS os alvos, incluindo 'installer_main' e 'ci_cd_visualizer'.
      - name: Setup vcpkg e Instalar dependências
        id: vcpkg
        uses: johnwason/vcpkg-action@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pkgs: curl lua nlohmann-json
          triplet: x64-windows
          run-vcpkg-integrate-install: true # <-- ESTA É A LINHA CRÍTICA

      # 5. Configura o projeto com CMake
      #    Mantemos a configuração explícita para garantir que o CMake e o vcpkg
      #    estejam alinhados desde o início.
      - name: Configurar CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}
        shell: powershell

      # 6. Compila o projeto
      #    Este passo agora funcionará porque o MSBuild (invocado pelo CMake)
      #    sabe onde encontrar as bibliotecas do vcpkg graças à integração.
      - name: Compilar Projeto
        run: cmake --build build --config Release --parallel
