# Copyright (C) 2025 Pedro Henrique / phkaiser13
# Windows-ci.yml - Workflow de Integração Contínua para o projeto gitph no Windows.
#
# Automatiza build, testes e upload de artefatos no Windows.
# SPDX-License-Identifier: Apache-2.0

name: Build do gitph (Windows)

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build e Teste no Windows
    runs-on: windows-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Instala dependências via choco (Chocolatey)
      #    Instala build-essential equivalente: Visual Studio Build Tools + cmake + pkg-config + Lua + curl + nlohmann-json
      - name: Instalar dependências do sistema
        shell: powershell
        run: |
          # Instala Chocolatey caso não esteja instalado
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force
            iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          }

          choco install -y visualstudio2019buildtools cmake pkgconfiglite lua curl nlohmann-json

      # 3. Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # 4. Setup Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      # 5. Configurar CMake e build
      - name: Configurar CMake
        shell: powershell
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Compilar Projeto
        shell: powershell
        run: cmake --build build --parallel

      # 6. Upload dos artefatos de build
      - name: Upload dos artefatos de build
        uses: actions/upload-artifact@v4
        with:
          name: gitph-build-artifacts
          path: |
            build\bin\
            src\plugins\
            LICENSE
