# windows_build.yml - Workflow Windows com integração correta do vcpkg

name: Build para Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    name: Build em Windows (MSVC)
    runs-on: windows-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # 3. Setup Rust com cache
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      # 4. Setup vcpkg e instalar dependências
      - name: Setup vcpkg e instalar dependências
        id: vcpkg
        uses: johnwason/vcpkg-action@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pkgs: curl lua nlohmann-json
          triplet: x64-windows
          run-vcpkg-integrate-install: true

      # 5. Debug para confirmar toolchain vcpkg
      - name: Confirmar toolchain do vcpkg
        run: |
          echo "Verificando toolchain file"
          dir C:/vcpkg/scripts/buildsystems
          Test-Path C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        shell: powershell

      # 6. Configurar CMake usando toolchain do vcpkg explicitamente
      - name: Configurar CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        shell: powershell

      # 7. Compilar projeto
      - name: Compilar Projeto
        run: cmake --build build --config Release --parallel
