# Copyright (C) 2025 Pedro Henrique / phkaiser13
# windows_build.yml - Workflow de Integração Contínua para Windows.
#
# Este workflow valida a compilação do projeto no ambiente Windows,
# garantindo que todas as dependências (C++, Rust, Go) são resolvidas
# e que o projeto compila com sucesso usando o toolchain do Visual Studio
# e o gerenciador de pacotes vcpkg.
#
# SPDX-License-Identifier: Apache-2.0

name: Build para Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    name: Build em Windows (MSVC)
    runs-on: windows-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # 3. Configura o ambiente Rust (com cache simples)
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Rust cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Rust cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}

      # 4. Setup vcpkg e Instalar dependências com integração correta
      - name: Setup vcpkg e Instalar dependências
        id: vcpkg
        uses: johnwason/vcpkg-action@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pkgs: curl lua nlohmann-json
          triplet: x64-windows
          integrate: true    # <-- CORREÇÃO AQUI

      # 5. Configura o projeto com CMake usando toolchain vcpkg
      - name: Configurar CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/hostedtoolcache/windows/vcpkg/scripts/buildsystems/vcpkg.cmake
        shell: powershell

      # 6. Compila o projeto
      - name: Compilar Projeto
        run: cmake --build build --config Release --parallel
